#!/bin/sh

ppgrep -x sxhkd > /dev/null || sxhkd &
picom &
feh --bg-fill ~/images/wallpaper/lagoon_nebula.jpg &

bspc rule -r "*"

bspc monitor -d 1 2 3 4 5

bspc config border_width 2
bspc config window_gap   10

bspc config normal_border_color \#282C34
bspc config active_border_color \#E06C75
bspc config focused_border_color \#61AFEF
bspc config presel_feedback_color \#61AFEF

bspc config focus_follows_pointer true
