[cursor]
style = "Block"

[font.bold]
family = "JetBrainsMono NL"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono NL"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono NL"
style = "Italic"

[font.normal]
family = "JetBrainsMono NL"
style = "Regular"

[font]
size = 12.0

[scrolling]
history = 10000

[terminal.shell]
program = "/bin/zsh"

[window]
decorations = "None"
opacity = 0.9

[general]
import = [
    "~/.config/alacritty-themes/themes/carbonfox.toml"
]
