[cursor]
style = "Block"

[font]
size = 12.0

[scrolling]
history = 10000

[terminal.shell]
program = "/bin/zsh"

[window]
opacity = 0.9

[general]
import = [
    "~/.config/alacritty-themes/themes/carbonfox.toml"
]
