[cursor]
style = "Block"

[font.normal]
family = "JetBrainsMono NL"

[font]
size = 12.0
offset = { x = 0, y = 1 }

[scrolling]
history = 10000

[terminal.shell]
program = "/bin/zsh"

[window]
decorations = "None"
opacity = 0.9

[general]
import = [
    "~/.config/alacritty-themes/themes/carbonfox.toml"
]
