import = [
    "~/.config/alacritty-themes/themes/carbonfox.toml"
]

[cursor]
style = "Block"

[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 12.0

[font.bold]
family = "monospace"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "monospace"
style = "Regular"

[scrolling]
history = 10000

[shell]
program = "/bin/zsh"

[window]
decorations = "none"
opacity = 0.9
